### ISSUE TITLE
The user should be able to set a default profile

### ISSUE THREAD

**Issue by derechtenap** [derechtenap/dartsmate#64]
# Tasks 
- [x] Allow the user to update the profile
- [x] Ask the user to create a profile, if there isn't a profile file on the client OS
- [x] Save the profile on the client OS
- [x] Let the user set a profile picture via file "upload" or webcam
